
DROP TABLE IF EXISTS ReceitaFederal..EmpresasResumos;
SELECT
		ANOABERTURA,
		UF,
		[SITUAÇÃO CADASTRAL],
		ANOSITUACAO,
		SIMPLESATIVO,
		MEIATIVO,
		FLAGSIMPLES,
		FLAGMEI,
		[PORTE DA EMPRESA],
		[QUALIFICAÇÃO DO RESPONSÁVEL],
		ANOADESAOMEI,
		ANOEXCLUSAOMEI,
		count([CNPJ BÁSICO]) as Empresas
into ReceitaFederal..EmpresasResumos
FROM (
		select
			ANOABERTURA,
			UF,
			[SITUAÇÃO CADASTRAL],
			[OPÇÃO PELO SIMPLES] as SIMPLESATIVO,
			[OPÇÃO PELO MEI] AS MEIATIVO,
			ANOADESAOMEI,
			ANOEXCLUSAOMEI,
			ANOSITUACAO,
			CASE
				WHEN [DATA DE OPÇÃO PELO SIMPLES] IS NULL THEN 'N' 
				WHEN [DATA DE OPÇÃO PELO SIMPLES] = 0 THEN 'N'
				WHEN [DATA DE OPÇÃO PELO SIMPLES] IS NOT NULL THEN 'S'
			END AS FLAGSIMPLES,
			CASE
				WHEN [DATA DE OPÇÃO PELO MEI] IS NULL THEN 'N'
				WHEN [DATA DE OPÇÃO PELO MEI] = 0 THEN 'N'
				WHEN [DATA DE OPÇÃO PELO MEI] IS NOT NULL THEN 'S'
			END AS FLAGMEI,
			[CNPJ BÁSICO],
			[PORTE DA EMPRESA],
			[QUALIFICAÇÃO DO RESPONSÁVEL]
		from (
			select
				FLOOR(t1.[DATA DE INÍCIO ATIVIDADE]/10000) AS ANOABERTURA, 
				FLOOR(t1.[DATA SITUAÇÃO CADASTRAL]/10000) AS ANOSITUACAO,
				FLOOR(t2.[DATA DE OPÇÃO PELO MEI]/10000) AS ANOADESAOMEI,
				FLOOR(t2.[DATA DE EXCLUSÃO DO MEI]/10000) AS ANOEXCLUSAOMEI,
				t1.[UF], 
				t1.[CNPJ BÁSICO], 
				t1.[SITUAÇÃO CADASTRAL],
				t2.[OPÇÃO PELO SIMPLES],
				t2.[DATA DE OPÇÃO PELO SIMPLES],
				t2.[DATA DE EXCLUSÃO DO SIMPLES],
				t2.[OPÇÃO PELO MEI],
				t2.[DATA DE OPÇÃO PELO MEI],
				t2.[DATA DE EXCLUSÃO DO MEI],
				t3.[PORTE DA EMPRESA],
				t3.[QUALIFICAÇÃO DO RESPONSÁVEL],
				t3.[CAPITAL SOCIAL DA EMPRESA]
			FROM ReceitaFederal..EmpresasNacionaisPeriodo t1
			left join ReceitaFederal..Simples t2 on t1.[CNPJ BÁSICO] = t2.[CNPJ BÁSICO]
			left join ReceitaFederal..Empresas t3 on t1.[CNPJ BÁSICO] = t3.[CNPJ BÁSICO]
		) a1
	) a2
where ANOABERTURA <> 2020
group by ANOABERTURA, UF, [SITUAÇÃO CADASTRAL], ANOSITUACAO, SIMPLESATIVO, MEIATIVO, FLAGSIMPLES, FLAGMEI, [PORTE DA EMPRESA], [QUALIFICAÇÃO DO RESPONSÁVEL], ANOADESAOMEI, ANOEXCLUSAOMEI
ORDER BY ANOABERTURA, UF;
