SELECT
      [CNAE FISCAL PRINCIPAL]
      ,[CEP]
      ,[UF]
      ,[NATUREZA JURÍDICA]
      ,[QUALIFICAÇÃO DO RESPONSÁVEL]
      ,[FLAGSIMPLES]
      ,[FLAGMEI]
      ,[ANOABERTURA]
      ,[POPULAÇÃO_ESTIMADA]
      ,[CD_MUNIC_INT]
      ,[PIB_2010]
      ,[PIB_2011]
      ,[PIB_2012]
      ,[PIB_2013]
      ,[PIB_2014]
      ,[PIB_2015]
      ,[PIB_2016]
      ,[PIB_2017]
      ,[PIB_2018]
      ,[PIB_2019]
      ,[PIB_2020]
      ,[PIB_2021]
      ,[INSS_QTD_25]
      ,[INSS_VLR_25]
      ,[NivelAlfabetizacao]
      ,[taxaSelicAbertura]
      ,[ClassicacaoDeViabilidada]
  FROM [ReceitaFederal].[dbo].[DadosEmpresasParaModeloV2]
  where [ClassicacaoDeViabilidada] <> 2 and [CNPJ BÁSICO]%100 in (87, 88, 89, 90, 91)