CREATE INDEX idx_empresas_filtro 
ON ReceitFederal..EmpresasNacionaisPeriodoAmostra([PORTE DA EMPRESA], [SITUAÇÃO CADASTRAL], [DATA DE INÍCIO ATIVIDADE])
INCLUDE ([CNPJ BÁSICO], [DATA SITUAÇÃO CADASTRAL], [CNAE FISCAL PRINCIPAL], CEP, UF, [NATUREZA JURÍDICA]);

CREATE INDEX idx_cod_municipios 
ON ReceitFederal..CodMunicipiosRF([CÓDIGO_DO_MUNICÍPIO_TOM]) 
INCLUDE (CÓDIGO_DO_MUNICÍPIO_IBGE);

CREATE INDEX idx_simples 
ON ReceitFederal..Simples([CNPJ BÁSICO]);

CREATE INDEX idx_dados_munic 
ON ReceitFederal..DadosMunic(ID_MUN);

CREATE INDEX idx_micro_abertas 
ON ReceitFederal..MICROEMPRESASABERTASPORANO([CNAE FISCAL PRINCIPAL], ANOABERTURA)
INCLUDE (CEP);

CREATE INDEX idx_micro_fechadas 
ON ReceitFederal..MICROEMPRESASFECHADASSPORANO([CNAE FISCAL PRINCIPAL], ANOBAIXA)
INCLUDE (CEP);

